In [2]:
from sklearn.cluster import KMeans
import numpy as np

import numpy as np

# Initialize an empty list to store the points
possible_points = []


for x1 in range(47):  # 0 to 47
    for x2 in range(47-x1):  # 0 to 47
        for x3 in range(47-x1-x2):  # 0 to 47
            if x1 + x2 + x3 == 46:
                possible_points.append([x1, x2, x3])
                
                



# Convert the list of points to a NumPy matrix
points_matrix = np.array(possible_points)

points = points_matrix

# Number of clusters
k = 100

# Initialize KMeans
kmeans = KMeans(n_clusters=k)

# Fit the model
kmeans.fit(points)

# Get cluster labels
labels = kmeans.labels_

# Get cluster centroids
centroids = kmeans.cluster_centers_
integer_matrix = centroids.astype(int)


C:\Users\moham\anaconda3_2\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\moham\anaconda3_2\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=5.
  warnings.warn(


[[17 26  1]
 [10  8 26]
 [28  9  7]
 [ 5 23 17]
 [27  4 14]
 [ 4 38  3]
 [ 5  2 37]
 [41  1  3]
 [21 17  7]
 [19  1 25]
 [ 3 16 25]
 [18  7 20]
 [ 6 29 10]
 [13 13 19]
 [26 18  0]
 [12 22 11]
 [ 1 10 34]
 [32  9  3]
 [38  1  6]
 [ 1 30 14]
 [ 4 33  8]
 [16 14 15]
 [11 33  0]
 [30  5 10]
 [15  1 28]
 [ 0  0 44]
 [ 5 19 20]
 [22  6 17]
 [12 16 16]
 [ 9  4 32]
 [25  2 17]
 [ 1  5 39]
 [25 16  4]
 [ 1 20 23]
 [24 13  8]
 [36  5  4]
 [10 27  7]
 [20 23  1]
 [ 6  7 31]
 [ 0 44  0]
 [29 15  1]
 [ 8 23 14]
 [14 18 12]
 [10 12 23]
 [12  1 32]
 [32 12  1]
 [ 8 33  4]
 [14  5 25]
 [ 0 17 27]
 [ 0 36  8]
 [17 23  5]
 [22  9 13]
 [ 7 15 23]
 [29  0 16]
 [26  8 11]
 [ 1 24 20]
 [ 1 27 17]
 [ 8 25 11]
 [ 5  5 35]
 [21  4 20]
 [ 2 42  1]
 [ 4 10 31]
 [11  5 28]
 [21 20  4]
 [36  8  1]
 [18 10 16]
 [ 5 13 27]
 [14 29  2]
 [ 9  1 35]
 [34  1  9]
 [39  5  1]
 [ 6 39  0]
 [16 10 19]
 [18 16 11]
 [ 4  1 41]
 [23  0 21]
 [ 9 19 16]
 [ 4 27 14]
 [ 1  7 36]
 [44  1  0]
 [ 9 16 20]
 [ 0 41  4]
 [ 5 35  4]
 [ 1

In [8]:
def adjust_matrix(matrix):
    new_matrix = np.copy(matrix)
    for i in range(matrix.shape[0]):
        row_sum = np.sum(new_matrix[i])
        while row_sum != 46:
            if row_sum <46:
                col_index = np.random.randint(3)
                new_matrix[i, col_index] += 1
                row_sum = np.sum(new_matrix[i])
            else:
                col_index = np.random.randint(3)
                new_matrix[i, col_index] -= 1
                row_sum = np.sum(new_matrix[i])                

    return new_matrix
integer_matrix = adjust_matrix(integer_matrix)

In [ ]:
import numpy as np

# Assuming you have an n*3 matrix
n = 100  # You can change n to any number
matrix = np.random.rand(n, 3)  # Replace this with your actual matrix

# Write the matrix as a list of 3D tuples to a text file
with open('../../data/matrix_as_tuples.txt', 'w') as file:
    for row in matrix:
        # Convert each row to a tuple and write it to the file
        file.write(f"{tuple(row)}\n")

In [11]:
np.savetxt('../../data/matrix.txt', integer_matrix, fmt='%.6f')

In [12]:
loaded_matrix = np.loadtxt('../../data/matrix.txt')